model:
    name: 'GRAPHEDX_Dual_xor'
    classPath: 'models.graphedx'
    LAMBDA: 1.0
    output_mode: 'L1'
    edge_scale: 1
    use_max : False
    use_second_sinkhorn : False
    use_second_sinkhorn_log : False 
    use_h_hp_node : True 
    use_m_ms_edge : True
