model:
    name: 'GRAPHEDX_xor_on_edge_label'
    classPath: 'models.graphedx_label'
    LAMBDA: 1.0
    beta: 1.0
    output_mode: 'L1'
    edge_scale: 1
    use_max : False
    use_second_sinkhorn : False
    use_second_sinkhorn_log : False 
    use_h_hp_node : False 
    use_m_ms_edge : False
