task:
  name: ''
  wandb_project: 'NoAttrGED'
  wandb_group: 
log:
  dir: 'logs'

base_dir: '.'

training:
  batch_size: 256
  device: 'cuda'
  dropout: 0
  learning_rate: 1e-3
  weight_decay: 5e-4
  num_epochs: 20000
  seed: 0
  run_till_early_stopping: True
  wandb_watch: False
  overwrite: False
  patience: 100
  weights_dir: 'weights'
  sinkhorn_temp: 0.1
  sinkhorn_noise: 0
  resume: False

dataset:
  name: 'linux'
  path: 'data'
  data_type: 'gmn'
  return_adj: False
  use_labels_as_features: True  

  node_ins_cost: 1
  node_del_cost: 1
  node_rel_cost: 1
  edge_ins_cost: 1
  edge_del_cost: 1
  edge_rel_cost: 0

model:
  name: ???
  is_baseline: False

gmn:
  filters_3: 10
  GMN_NPROPLAYERS: 5
  variant: shallow

mode: no_attr